name: movie-api

networks:
  backend-api:
    driver: bridge

services:

  database:
    image: postgres
    container_name: database
    restart: always
    shm_size: 100mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zyRNNaHnN3U6LTfVCHm9aKSE7KVAAc
      POSTGRES_PASSWORD: wwZFGVt3neZ6J9hmR29ur8admVGv
      POSTGRES_DB: db-movie-api
    networks:
      - backend-api

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - database
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    networks:
      - backend-api