name: movie-api

networks:
  backend-api:
    driver: bridge

services:

  database:
    image: postgres:17.1
    container_name: database
    restart: always
    shm_size: 100mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: movie_api_user
      POSTGRES_PASSWORD: wwZFGVt3neZ6J9hmR29ur8admVGv
      POSTGRES_DB: db_movie_api
    networks:
      - backend-api

  cloudbeaver:
    image: dbeaver/cloudbeaver:24.2.5
    container_name: cloudbeaver
    depends_on:
      - database
    restart: always
    ports:
      - "8978:8978"
    environment:
      CLOUDBEAVER_USER: cbadmin
      CLOUDBEAVER_PASSWORD: g7GBZmTXS6qv2rV2RKPwnNU6sBDx4J
    networks:
      - backend-api